# Generated by Django 2.2.6 on 2021-08-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20181115_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='stepsAndIngredients',
            field=models.CharField(default='temp', max_length=5000),
            preserve_default=False,
        ),
    ]
